# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Voice(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, gender: str=None, age: int=None):
        """
        Voice - a model defined in Swagger

        :param id: The id of this Voice.
        :type id: int
        :param name: The name of this Voice.
        :type name: str
        :param gender: The gender of this Voice.
        :type gender: str
        :param age: The age of this Voice.
        :type age: int
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'gender': str,
            'age': int
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'gender': 'gender',
            'age': 'age'
        }

        self._id = id
        self._name = name
        self._gender = gender
        self._age = age

    @classmethod
    def from_dict(cls, dikt) -> 'Voice':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Voice of this Voice.
        :rtype: Voice
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """
        Gets the id of this Voice.

        :return: The id of this Voice.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """
        Sets the id of this Voice.

        :param id: The id of this Voice.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """
        Gets the name of this Voice.

        :return: The name of this Voice.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this Voice.

        :param name: The name of this Voice.
        :type name: str
        """

        self._name = name

    @property
    def gender(self) -> str:
        """
        Gets the gender of this Voice.

        :return: The gender of this Voice.
        :rtype: str
        """
        return self._gender

    @gender.setter
    def gender(self, gender: str):
        """
        Sets the gender of this Voice.

        :param gender: The gender of this Voice.
        :type gender: str
        """

        self._gender = gender

    @property
    def age(self) -> int:
        """
        Gets the age of this Voice.

        :return: The age of this Voice.
        :rtype: int
        """
        return self._age

    @age.setter
    def age(self, age: int):
        """
        Sets the age of this Voice.

        :param age: The age of this Voice.
        :type age: int
        """

        self._age = age

